#!/usr/bin/env python
import sys, os, xmlrpclib, spending

transactions = spending.load_transactions( "./" )
p = xmlrpclib.ServerProxy("https://www.studentrobotics.org/trac/rpc")
tickets = p.ticket.query( "component=purchasing&max=0&resolution!=invalid&resolution!=wontfix&resolution!=duplicate" )

counts = {}
for t in tickets:
    if t < 821 and t not in []:
        "Tickets before #839 except for those listed above weren't budgeted"
        continue

    counts[t] = 0

for t in transactions:
    counts[t.trac] += 1

missing = []
for tnum, count in counts.iteritems():
    if count == 0:
        missing.append( tnum )

missing.sort()

if len(missing):
    print "Trac tickets with no spending.git entry:"
    for t in missing:
        print "{0:10} -- http://srobo.org/trac/ticket/{0}".format(t)

